USE [master]
GO

/****** Object:  Database [Icecream_parlor]    Script Date: 4/10/2018 12:21:33 AM ******/
CREATE DATABASE [Icecream_parlor]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Icecream_parlor', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2017\MSSQL\DATA\Icecream_parlor.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Icecream_parlor_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2017\MSSQL\DATA\Icecream_parlor_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Icecream_parlor] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Icecream_parlor].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Icecream_parlor] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Icecream_parlor] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Icecream_parlor] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Icecream_parlor] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Icecream_parlor] SET ARITHABORT OFF 
GO

ALTER DATABASE [Icecream_parlor] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Icecream_parlor] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Icecream_parlor] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Icecream_parlor] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Icecream_parlor] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Icecream_parlor] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Icecream_parlor] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Icecream_parlor] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Icecream_parlor] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Icecream_parlor] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Icecream_parlor] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Icecream_parlor] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Icecream_parlor] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Icecream_parlor] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Icecream_parlor] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Icecream_parlor] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Icecream_parlor] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Icecream_parlor] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Icecream_parlor] SET  MULTI_USER 
GO

ALTER DATABASE [Icecream_parlor] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Icecream_parlor] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Icecream_parlor] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Icecream_parlor] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Icecream_parlor] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Icecream_parlor] SET  READ_WRITE 
GO

